# -*- coding: utf-8 -*-
"""deepfake_detection_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0LdfFgl0eYg8X2Sx5Yk0ytBG2ynRl6U

# imports
"""

!pip install grad-cam

from google.colab import drive

import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import DataLoader, Subset, random_split, ConcatDataset

from torchvision import datasets, transforms, models
from torchvision.models import ResNet50_Weights

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report,
    precision_score,
    recall_score,
    f1_score,
    roc_curve,
    auc,
    precision_recall_curve
)

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

from matplotlib.colors import LinearSegmentedColormap

"""# data loading and transformation"""

drive.mount('/content/drive')

base_dir = "/content/drive/MyDrive/deepfake_detection/deepfake_data/train"

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

dataset = datasets.ImageFolder(
    f"{base_dir}/fold1",
    transform=transform
)

print(len(dataset))
print(dataset.class_to_idx)

loader = DataLoader(dataset, batch_size=32, shuffle=True)

images, labels = next(iter(loader))

print(images.shape)
print(labels[:5])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

"""# CNN

## set up
"""

class SimpleCNNBaseline(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(3, 32 , 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 28 * 28, 128),
            nn.ReLU(),
            nn.Linear(128, 2)
        )

    def forward(self, x):
        x = self.conv(x)
        return self.fc(x)

class SimpleCNN4Layers(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(128, 256, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256 * 14 * 14, 128),
            nn.ReLU(),
            nn.Linear(128, 2)
        )

    def forward(self, x):
        x = self.conv(x)
        return self.fc(x)

class SimpleCNNDropout(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(3, 32 , 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 28 * 28, 128),
            nn.ReLU(),

            nn.Dropout(0.5),

            nn.Linear(128, 2)
        )

    def forward(self, x):
        x = self.conv(x)
        return self.fc(x)

class SimpleCNNAvgpool(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(3, 32 , 3, padding=1),
            nn.ReLU(),
            nn.AvgPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.ReLU(),
            nn.AvgPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.ReLU(),
            nn.AvgPool2d(2)
        )

        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 28 * 28, 128),
            nn.ReLU(),
            nn.Linear(128, 2)
        )

    def forward(self, x):
        x = self.conv(x)
        return self.fc(x)

"""## training on first folder of training data"""

experiment_name = "cnn_baseline"

num_conv_layers = 3
learning_rate = 0.001
epochs = 2
batch_size = 32

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):
    model.train()
    running_loss = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")


os.makedirs("/content/drive/MyDrive/deepfake_detection/models", exist_ok=True)

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
    )
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

experiment_name = "cnn_ep3"

learning_rate = 0.001
epochs = 3
batch_size = 32
num_conv_layers = 3

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):
    model.train()
    running_loss = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")


os.makedirs("/content/drive/MyDrive/deepfake_detection/models", exist_ok=True)

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
    )
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

experiment_name = "cnn_ep3_lr0005"

num_conv_layers = 3
learning_rate = 0.0005
epochs = 3
batch_size = 32

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):
    model.train()
    running_loss = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")


os.makedirs("/content/drive/MyDrive/deepfake_detection/models", exist_ok=True)

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
    )
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

experiment_name = "cnn_avgpool"

num_conv_layers = 3
learning_rate = 0.0005
epochs = 3
batch_size = 32

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):
    model.train()
    running_loss = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")


os.makedirs("/content/drive/MyDrive/deepfake_detection/models", exist_ok=True)

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = SimpleCNNAvgpool().to(device)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
    )
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

experiment_name = "cnn_4layers"

num_conv_layers = 4
learning_rate = 0.001
epochs = 3
batch_size = 32

model = SimpleCNN4Layers().to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):

    model.train()

    running_loss = 0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("Model saved successfully.")

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = SimpleCNN4Layers().to(device)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
    )
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

experiment_name = "cnn_dropout_lr0005"

num_conv_layers = 3
learning_rate = 0.0005
epochs = 3
batch_size = 32

model = SimpleCNNDropout().to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):

    model.train()
    running_loss = 0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)
        optimizer.zero_grad()

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("Model saved successfully.")

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = SimpleCNNDropout().to(device)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
    )
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

"""## experimental results and model selection"""

results = []

with open(
    "/content/drive/MyDrive/deepfake_detection/models/results.txt",
    "r"
) as f:

    lines = f.readlines()

experiment = None

for line in lines:

    line = line.strip()

    if line.startswith("Experiment:"):
        experiment = line.replace("Experiment:", "").strip()

    elif line.startswith("Validation Accuracy:"):
        accuracy = float(
            line.replace("Validation Accuracy:", "").strip()
        )

        results.append({
            "Experiment": experiment,
            "Validation Accuracy": accuracy
        })

results = pd.DataFrame(results)

results = results.sort_values(
    by="Validation Accuracy",
    ascending=False
)

results = results.reset_index(drop=True)

results

best_model = results.iloc[0]

with open(
    "/content/drive/MyDrive/deepfake_detection/models/continued_training_results.txt",
    "w"
) as f:

    f.write("====================\n")
    f.write("Evaluation after fold1 training\n")
    f.write(
        f"Validation Accuracy: "
        f"{best_model['Validation Accuracy']:.4f}\n"
    )

print("Initial result saved successfully.")

plt.figure(figsize=(9,5))

colors = ["maroon"] * len(results)
colors[0] = "crimson"

plt.bar(
    results["Experiment"],
    results["Validation Accuracy"],
    color=colors
)

plt.title("SimpleCNN Hyperparameter Tuning")
plt.ylabel("Validation Accuracy")
plt.xticks(rotation=20)
plt.grid(axis="y")

plt.show()

"""## continued training on second folder"""

experiment_name = "cnn_fold2_finetuned"

learning_rate = 0.0005
epochs = 3
batch_size = 32

train_dataset = datasets.ImageFolder(
    f"/content/drive/MyDrive/deepfake_detection/deepfake_data/train/fold2",
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/deepfake_detection/models/cnn_ep3_lr0005.pth")
)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):

    model.train()

    running_loss = 0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("Model saved successfully.")

validation_dataset = datasets.ImageFolder(
    f"/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/deepfake_detection/models/cnn_fold2_finetuned.pth")
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

accuracy = correct / total

print(f"Validation Accuracy after fold2 training: {accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/continued_training_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write("After continued training on fold2\n")
    f.write(f"Validation Accuracy: {accuracy:.4f}\n")

print("Results saved successfully.")

"""## continued training on third folder"""

experiment_name = "cnn_fold3_finetuned"

learning_rate = 0.0005
epochs = 3
batch_size = 32

train_dataset = datasets.ImageFolder(
    f"/content/drive/MyDrive/deepfake_detection/deepfake_data/train/fold3",
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/deepfake_detection/models/cnn_fold2_finetuned.pth")
)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):

    model.train()

    running_loss = 0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("Model saved successfully.")

validation_dataset = datasets.ImageFolder(
    f"/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/deepfake_detection/models/cnn_fold3_finetuned.pth")
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

accuracy = correct / total

print(f"Validation Accuracy after fold3 training: {accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/continued_training_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write("After continued training on fold3\n")
    f.write(f"Validation Accuracy: {accuracy:.4f}\n")

print("Results saved successfully.")

"""## continued training on fourth folder"""

experiment_name = "cnn_fold4_finetuned"

learning_rate = 0.0005
epochs = 3
batch_size = 32

train_dataset = datasets.ImageFolder(
    f"/content/drive/MyDrive/deepfake_detection/deepfake_data/train/fold4",
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/deepfake_detection/models/cnn_fold3_finetuned.pth")
)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):

    model.train()

    running_loss = 0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("Model saved successfully.")

validation_dataset = datasets.ImageFolder(
    f"/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/deepfake_detection/models/cnn_fold4_finetuned.pth")
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

accuracy = correct / total

print(f"Validation Accuracy after fold4 training: {accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/continued_training_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write("After continued training on fold4\n")
    f.write(f"Validation Accuracy: {accuracy:.4f}\n")

print("Results saved successfully.")

"""## continued training on fifth folder"""

experiment_name = "cnn_fold5_finetuned"

learning_rate = 0.0005
epochs = 3
batch_size = 32

train_dataset = datasets.ImageFolder(
    f"/content/drive/MyDrive/deepfake_detection/deepfake_data/train/fold5",
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/deepfake_detection/models/cnn_fold4_finetuned.pth")
)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):

    model.train()

    running_loss = 0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("Model saved successfully.")

validation_dataset = datasets.ImageFolder(
    f"/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/deepfake_detection/models/cnn_fold5_finetuned.pth")
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

accuracy = correct / total

print(f"Validation Accuracy after fold5 training: {accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/continued_training_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write("After continued training on fold5\n")
    f.write(f"Validation Accuracy: {accuracy:.4f}\n")

print("Results saved successfully.")

"""## final evaluation on the test set"""

batch_size = 32

os.makedirs(
    "/content/drive/MyDrive/deepfake_detection/results",
    exist_ok=True
)

test_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/test",
    transform=transform
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False
)

model = SimpleCNNBaseline()

model.load_state_dict(
    torch.load(
        "/content/drive/MyDrive/deepfake_detection/models/cnn_fold5_finetuned.pth"
    )
)

model = model.to(device)
model.eval()

correct = 0
total = 0

all_labels = []
all_predictions = []
all_probabilities = []

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        probabilities = torch.softmax(outputs, dim=1)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())
        all_probabilities.extend(probabilities[:, 1].cpu().numpy())

accuracy = correct / total
precision = precision_score(all_labels, all_predictions)
recall = recall_score(all_labels, all_predictions)
f1 = f1_score(all_labels, all_predictions)

report = classification_report(
    all_labels,
    all_predictions,
    target_names=test_dataset.classes
)

cm = confusion_matrix(all_labels, all_predictions)

fpr, tpr, _ = roc_curve(all_labels, all_probabilities)
roc_auc = auc(fpr, tpr)

precision_curve, recall_curve, _ = precision_recall_curve(
    all_labels,
    all_probabilities
)

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}")

print("\nClassification Report:\n")
print(report)

print("Confusion Matrix:\n")
print(cm)

with open(
    "/content/drive/MyDrive/deepfake_detection/results/simplecnn_test_results.txt",
    "w"
) as f:

    f.write("===== SimpleCNN - Test Results =====\n\n")

    f.write(f"Accuracy : {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall   : {recall:.4f}\n")
    f.write(f"F1-score : {f1:.4f}\n")
    f.write(f"ROC AUC  : {roc_auc:.4f}\n\n")

    f.write("Classification Report:\n")
    f.write(report)
    f.write("\n")

    f.write("Confusion Matrix:\n")
    f.write("Predicted ->\tFake\tReal\n")
    f.write(f"Actual Fake\t{cm[0,0]}\t{cm[0,1]}\n")
    f.write(f"Actual Real\t{cm[1,0]}\t{cm[1,1]}\n")

print("\nResults saved successfully.")

save_dir = "/content/drive/MyDrive/deepfake_detection/figures/simplecnn"

os.makedirs(save_dir, exist_ok=True)

maroon_cmap = LinearSegmentedColormap.from_list(
    "maroon_cmap",
    ["#F5E6E8", "#800020"]
)


fig, ax = plt.subplots(figsize=(7, 6))

im = ax.imshow(
    cm,
    interpolation="nearest",
    cmap=maroon_cmap
)

fig.colorbar(im, ax=ax)

ax.set(
    xticks=np.arange(len(test_dataset.classes)),
    yticks=np.arange(len(test_dataset.classes)),
    xticklabels=test_dataset.classes,
    yticklabels=test_dataset.classes,
    xlabel="Predicted label",
    ylabel="True label",
    title="Confusion Matrix - SimpleCNN"
)

threshold = cm.max() / 2

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):

        ax.text(
            j,
            i,
            format(cm[i, j], "d"),
            ha="center",
            va="center",
            color="white"
            if cm[i, j] > threshold
            else "black",
            fontsize=13
        )

fig.tight_layout()

plt.savefig(
    f"{save_dir}/confusion_matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.savefig(
    f"{save_dir}/confusion_matrix.pdf",
    bbox_inches="tight"
)

plt.show()
plt.close()

save_dir = "/content/drive/MyDrive/deepfake_detection/figures/simplecnn"

os.makedirs(save_dir, exist_ok=True)

maroon = "#800020"


plt.figure(figsize=(7,6))

plt.plot(
    fpr,
    tpr,
    color=maroon,
    linewidth=2,
    label=f"AUC = {roc_auc:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    "--",
    color=maroon
)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - SimpleCNN")
plt.legend(loc="lower right")

plt.savefig(
    f"{save_dir}/roc_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.close()


plt.figure(figsize=(7,6))

plt.plot(
    recall_curve,
    precision_curve,
    color=maroon,
    linewidth=2
)

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve - SimpleCNN")

plt.savefig(
    f"{save_dir}/precision_recall_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.close()

print("All figures saved successfully.")

"""## Grad-CAM visualization"""

model = SimpleCNNBaseline().to(device)

model.load_state_dict(
    torch.load(
        "/content/drive/MyDrive/deepfake_detection/models/cnn_fold5_finetuned.pth"
    )
)

model.eval()

fake_image_path = "/content/drive/MyDrive/deepfake_detection/deepfake_data/test/Fake/fake_126.jpg"

real_image_path = "/content/drive/MyDrive/deepfake_detection/deepfake_data/test/Real/real_385.jpg"

pil_image_fake = Image.open(
    fake_image_path
).convert("RGB")

pil_image_fake = pil_image_fake.resize((224,224))

input_tensor_fake = transform(
    pil_image_fake
).unsqueeze(0).to(device)

rgb_img_fake = np.array(
    pil_image_fake
).astype(np.float32) / 255.0

pil_image_real = Image.open(
    real_image_path
).convert("RGB")

pil_image_real = pil_image_real.resize((224,224))

input_tensor_real = transform(
    pil_image_real
).unsqueeze(0).to(device)

rgb_img_real = np.array(
    pil_image_real
).astype(np.float32) / 255.0

target_layer = model.conv[-2]

cam = GradCAM(
    model=model,
    target_layers=[target_layer]
)

grayscale_cam_fake = cam(
    input_tensor=input_tensor_fake
)[0]

visualization_fake = show_cam_on_image(
    rgb_img_fake,
    grayscale_cam_fake,
    use_rgb=True
)

grayscale_cam_real = cam(
    input_tensor=input_tensor_real
)[0]

visualization_real = show_cam_on_image(
    rgb_img_real,
    grayscale_cam_real,
    use_rgb=True
)

plt.figure(figsize=(14,10))

plt.subplot(2,2,1)
plt.imshow(rgb_img_fake)
plt.title("Fake - Original")
plt.axis("off")

plt.subplot(2,2,2)
plt.imshow(visualization_fake)
plt.title("Fake - Grad-CAM")
plt.axis("off")

plt.subplot(2,2,3)
plt.imshow(rgb_img_real)
plt.title("Real - Original")
plt.axis("off")

plt.subplot(2,2,4)
plt.imshow(visualization_real)
plt.title("Real - Grad-CAM")
plt.axis("off")

plt.tight_layout()

plt.savefig(
    "/content/drive/MyDrive/deepfake_detection/models/gradcam_fake_real.png"
)

plt.show()

print("Grad-CAM visualization saved successfully.")

"""# resnet50

## training on first folder of training data
"""

experiment_name = "resnet50_lr0001"

learning_rate = 0.0001
epochs = 3

model = models.resnet50(pretrained=True)

for param in model.parameters():
    param.requires_grad = False

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.fc.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):

    model.train()

    running_loss = 0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("ResNet50 model saved successfully.")

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/resnet_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write(f"Learning Rate: {learning_rate}\n")
    f.write(f"Epochs: {epochs}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

experiment_name = "resnet50_lr001"

learning_rate = 0.001
epochs = 3

from torchvision.models import ResNet50_Weights

model = models.resnet50(
    weights=ResNet50_Weights.DEFAULT
)

for param in model.parameters():
    param.requires_grad = False

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.fc.parameters(),
    lr=learning_rate
)

for epoch in range(epochs):

    model.train()

    running_loss = 0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("ResNet50 model saved successfully.")

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/resnet_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write(f"Learning Rate: {learning_rate}\n")
    f.write(f"Epochs: {epochs}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

experiment_name = "resnet50_partial_unfreeze"

learning_rate = 0.0001
epochs = 3

model = models.resnet50(
    weights=ResNet50_Weights.DEFAULT
)

for param in model.parameters():
    param.requires_grad = False

for param in model.layer4.parameters():
    param.requires_grad = True

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    filter(
        lambda p: p.requires_grad,
        model.parameters()
    ),
    lr=learning_rate
)

for epoch in range(epochs):

    model.train()

    running_loss = 0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")


torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("ResNet50 model saved successfully.")

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/resnet_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write("Partial Unfreeze: layer4\n")
    f.write(f"Learning Rate: {learning_rate}\n")
    f.write(f"Epochs: {epochs}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

experiment_name = "resnet50_partial_unfreeze_ep5"

learning_rate = 0.0001
epochs = 5

model = models.resnet50(
    weights=ResNet50_Weights.DEFAULT
)

for param in model.parameters():
    param.requires_grad = False

for param in model.layer4.parameters():
    param.requires_grad = True

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    filter(
        lambda p: p.requires_grad,
        model.parameters()
    ),
    lr=learning_rate
)

for epoch in range(epochs):

    model.train()

    running_loss = 0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("ResNet50 model saved successfully.")

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        "/content/drive/MyDrive/deepfake_detection/models/resnet50_partial_unfreeze_ep5.pth"
    )
)

model = model.to(device)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/models/resnet_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write("Partial Unfreeze: layer4\n")
    f.write(f"Learning Rate: {learning_rate}\n")
    f.write(f"Epochs: {epochs}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

experiment_name = "resnet50_partial_unfreeze_lr001"

learning_rate = 0.001
epochs = 3

model = models.resnet50(
    weights=ResNet50_Weights.DEFAULT
)


for param in model.parameters():
    param.requires_grad = False


for param in model.layer4.parameters():
    param.requires_grad = True


model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model = model.to(device)


criterion = nn.CrossEntropyLoss()


optimizer = torch.optim.Adam(
    filter(
        lambda p: p.requires_grad,
        model.parameters()
    ),
    lr=learning_rate
)


for epoch in range(epochs):

    model.train()

    running_loss = 0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("Final ResNet50 model saved successfully.")

experiment_name = "resnet50_partial_unfreeze_lr001"

learning_rate = 0.001
epochs = 3


validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)


model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
    )
)

model = model.to(device)


model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")


with open(
    "/content/drive/MyDrive/deepfake_detection/models/resnet_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(f"Experiment: {experiment_name}\n")
    f.write("Partial Unfreeze: layer4\n")
    f.write(f"Learning Rate: {learning_rate}\n")
    f.write(f"Epochs: {epochs}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Results saved successfully.")

"""## experimental results and model selection"""

results = []

with open(
    "/content/drive/MyDrive/deepfake_detection/results/resnet_results.txt",
    "r"
) as f:

    lines = f.readlines()

experiment = None

for line in lines:

    line = line.strip()

    if line.startswith("Experiment:"):
        experiment = line.replace("Experiment:", "").strip()

    elif line.startswith("Validation Accuracy:"):
        accuracy = float(
            line.replace("Validation Accuracy:", "").strip()
        )

        results.append({
            "Experiment": experiment,
            "Validation Accuracy": accuracy
        })

results = pd.DataFrame(results)

results = results.sort_values(
    by="Validation Accuracy",
    ascending=False
)

results = results.reset_index(drop=True)

results

best_model = results.iloc[0]

with open(
    "/content/drive/MyDrive/deepfake_detection/results/resnet_continued_training_results.txt",
    "w"
) as f:

    f.write("====================\n")
    f.write("Evaluation after fold1 training\n")
    f.write(
        f"Validation Accuracy: "
        f"{best_model['Validation Accuracy']:.4f}\n"
    )

print("Initial result saved successfully.")

results["Experiment"] = results["Experiment"].replace({
    "resnet50_lr0001": "LR = 0.0001",
    "resnet50_lr001": "LR = 0.001",
    "resnet50_partial_unfreeze": "Partial Unfreeze",
    "resnet50_partial_unfreeze_ep5": "Partial Unfreeze (5 epochs)",
    "resnet50_partial_unfreeze_lr001": "Partial Unfreeze + LR = 0.001"
})

plt.figure(figsize=(9,5))

colors = ["maroon"] * len(results)
colors[0] = "crimson"

plt.bar(
    results["Experiment"],
    results["Validation Accuracy"],
    color=colors
)

plt.title("ResNet50 Hyperparameter Tuning")
plt.ylabel("Validation Accuracy")
plt.xticks(rotation=20)
plt.grid(axis="y")

plt.show()

"""## continued training on second folder"""

experiment_name = "resnet50_partial_fold2_finetuned"

learning_rate = 0.0001
epochs = 3
batch_size = 32

train_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/train/fold2",
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

for param in model.parameters():
    param.requires_grad = False

for param in model.layer4.parameters():
    param.requires_grad = True

for param in model.fc.parameters():
    param.requires_grad = True

model.load_state_dict(
    torch.load(
        "/content/drive/MyDrive/deepfake_detection/models/resnet50_partial_unfreeze.pth",
        map_location=device
    )
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

for epoch in range(epochs):

    optimizer = torch.optim.Adam(
        filter(
            lambda p: p.requires_grad,
            model.parameters()
        ),
        lr=learning_rate
    )

    model.train()

    running_loss = 0.0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/"
    f"{experiment_name}.pth"
)

print("Final Fold2 model saved.")

experiment_name = "resnet50_partial_fold2_finetuned"

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth",
        map_location=device
    )
)

model = model.to(device)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

validation_accuracy = correct / total

print(
    f"Validation Accuracy: {validation_accuracy:.4f}"
)

with open(
    "/content/drive/MyDrive/deepfake_detection/results/resnet_continued_training_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(
        f"After continued training on {experiment_name}\n"
    )
    f.write(
        f"Validation Accuracy: {validation_accuracy:.4f}\n"
    )

print("Validation result saved successfully.")

"""## continued training on third folder"""

experiment_name = "resnet50_partial_fold3_finetuned"

learning_rate = 0.0001
epochs = 3
batch_size = 32

train_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/train/fold3",
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

for param in model.parameters():
    param.requires_grad = False

for param in model.layer4.parameters():
    param.requires_grad = True

for param in model.fc.parameters():
    param.requires_grad = True

model.load_state_dict(
    torch.load(
        "/content/drive/MyDrive/deepfake_detection/models/resnet50_partial_fold2_finetuned.pth",
        map_location=device
    )
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

for epoch in range(epochs):

    optimizer = torch.optim.Adam(
        filter(
            lambda p: p.requires_grad,
            model.parameters()
        ),
        lr=learning_rate
    )

    model.train()

    running_loss = 0.0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/"
    f"{experiment_name}.pth"
)

print("Final Fold3 model saved.")

experiment_name = "resnet50_partial_fold3_finetuned"

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth",
        map_location=device
    )
)

model = model.to(device)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

validation_accuracy = correct / total

print(
    f"Validation Accuracy: {validation_accuracy:.4f}"
)

with open(
    "/content/drive/MyDrive/deepfake_detection/results/resnet_continued_training_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(
        f"After continued training on {experiment_name}\n"
    )
    f.write(
        f"Validation Accuracy: {validation_accuracy:.4f}\n"
    )

print("Validation result saved successfully.")

"""## continued training on fourth folder"""

experiment_name = "resnet50_partial_fold4_finetuned"

learning_rate = 0.0001
epochs = 3
batch_size = 32

train_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/train/fold4",
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

for param in model.parameters():
    param.requires_grad = False

for param in model.layer4.parameters():
    param.requires_grad = True

for param in model.fc.parameters():
    param.requires_grad = True

model.load_state_dict(
    torch.load(
        "/content/drive/MyDrive/deepfake_detection/models/resnet50_partial_fold3_finetuned.pth",
        map_location=device
    )
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

for epoch in range(epochs):

    optimizer = torch.optim.Adam(
        filter(
            lambda p: p.requires_grad,
            model.parameters()
        ),
        lr=learning_rate
    )

    model.train()

    running_loss = 0.0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/"
    f"{experiment_name}.pth"
)

print("Final Fold4 model saved.")

experiment_name = "resnet50_partial_fold4_finetuned"

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth",
        map_location=device
    )
)

model = model.to(device)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

validation_accuracy = correct / total

print(
    f"Validation Accuracy: {validation_accuracy:.4f}"
)

with open(
    "/content/drive/MyDrive/deepfake_detection/results/resnet_continued_training_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(
        f"After continued training on {experiment_name}\n"
    )
    f.write(
        f"Validation Accuracy: {validation_accuracy:.4f}\n"
    )

print("Validation result saved successfully.")

"""## continued training on fifth folder"""

experiment_name = "resnet50_partial_fold5_finetuned"

learning_rate = 0.0001
epochs = 3
batch_size = 32

train_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/train/fold5",
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

for param in model.parameters():
    param.requires_grad = False

for param in model.layer4.parameters():
    param.requires_grad = True

for param in model.fc.parameters():
    param.requires_grad = True

model.load_state_dict(
    torch.load(
        "/content/drive/MyDrive/deepfake_detection/models/resnet50_partial_fold4_finetuned.pth",
        map_location=device
    )
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

for epoch in range(epochs):

    optimizer = torch.optim.Adam(
        filter(
            lambda p: p.requires_grad,
            model.parameters()
        ),
        lr=learning_rate
    )

    model.train()

    running_loss = 0.0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/"
    f"{experiment_name}.pth"
)

print("Final Fold5 model saved.")

experiment_name = "resnet50_partial_fold5_finetuned"

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth",
        map_location=device
    )
)

model = model.to(device)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

validation_accuracy = correct / total

print(
    f"Validation Accuracy: {validation_accuracy:.4f}"
)

with open(
    "/content/drive/MyDrive/deepfake_detection/results/resnet_continued_training_results.txt",
    "a"
) as f:

    f.write("\n====================\n")
    f.write(
        f"After continued training on {experiment_name}\n"
    )
    f.write(
        f"Validation Accuracy: {validation_accuracy:.4f}\n"
    )

print("Validation result saved successfully.")

experiment_name = "resnet50_fold5_finetuned"

learning_rate = 0.0001
epochs = 1

model = models.resnet50(weights=None)

num_features = model.fc.in_features
model.fc = nn.Linear(num_features, 2)

for param in model.parameters():
    param.requires_grad = False

for param in model.layer4.parameters():
    param.requires_grad = True

for param in model.fc.parameters():
    param.requires_grad = True

model.load_state_dict(torch.load(
    "/content/drive/MyDrive/deepfake_detection/models/resnet50_fold4_finetuned.pth"
))

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=learning_rate
)

model.train()

for epoch in range(epochs):

    running_loss = 0.0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch 1, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    "/content/drive/MyDrive/deepfake_detection/models/resnet50_fold5_finetuned_epoch1.pth"
)

print("Checkpoint after epoch 1 saved.")

import torch
import torch.nn as nn
from torchvision import models

learning_rate = 0.0001
epochs = 1

model = models.resnet50(weights=None)

num_features = model.fc.in_features
model.fc = nn.Linear(num_features, 2)

for param in model.parameters():
    param.requires_grad = False

for param in model.layer4.parameters():
    param.requires_grad = True

for param in model.fc.parameters():
    param.requires_grad = True

model.load_state_dict(torch.load(
    "/content/drive/MyDrive/deepfake_detection/models/resnet50_fold5_finetuned_epoch1.pth"
))

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=learning_rate
)

model.train()

for epoch in range(epochs):

    running_loss = 0.0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch 2, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    "/content/drive/MyDrive/deepfake_detection/models/resnet50_fold5_finetuned_epoch2.pth"
)

print("Checkpoint after epoch 2 saved.")

experiment_name = "resnet50_fold5_finetuned"

learning_rate = 0.0001
epochs = 1

model = models.resnet50(weights=None)

num_features = model.fc.in_features
model.fc = nn.Linear(num_features, 2)

for param in model.parameters():
    param.requires_grad = False

for param in model.layer4.parameters():
    param.requires_grad = True

for param in model.fc.parameters():
    param.requires_grad = True

model.load_state_dict(torch.load(
    "/content/drive/MyDrive/deepfake_detection/models/resnet50_fold5_finetuned_epoch2.pth"
))

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=learning_rate
)

model.train()

for epoch in range(epochs):

    running_loss = 0.0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch 3, Loss: {running_loss:.4f}")

torch.save(
    model.state_dict(),
    f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
)

print("Final model saved.")

batch_size = 32

validation_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/validation",
    transform=transform
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=batch_size,
    shuffle=False
)

experiment_name = "resnet50_fold5_finetuned"

model = models.resnet50(weights=None)

num_features = model.fc.in_features
model.fc = nn.Linear(num_features, 2)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth"
    )
)

model = model.to(device)
model.eval()

correct = 0
total = 0

with torch.no_grad():
    for images, labels in validation_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

validation_accuracy = correct / total

print(f"Validation Accuracy: {validation_accuracy:.4f}")

with open("/content/drive/MyDrive/deepfake_detection/models/resnet_continued_training_results.txt", "a") as f:
    f.write("\n====================\n")
    f.write(f"After continued training on {experiment_name}\n")
    f.write(f"Validation Accuracy: {validation_accuracy:.4f}\n")

print("Validation result saved.")

"""## final evaluation on the test set"""

experiment_name = "resnet50_partial_fold5_finetuned"

model_path = (
    "/content/drive/MyDrive/deepfake_detection/models/"
    f"{experiment_name}.pth"
)

results_dir = (
    "/content/drive/MyDrive/deepfake_detection/results"
)

figures_dir = (
    "/content/drive/MyDrive/deepfake_detection/figures/resnet50"
)

os.makedirs(results_dir, exist_ok=True)
os.makedirs(figures_dir, exist_ok=True)

batch_size = 32

test_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/test",
    transform=transform
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        model_path,
        map_location=device
    )
)

model = model.to(device)
model.eval()

correct = 0
total = 0

all_labels = []
all_predictions = []
all_probabilities = []

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        probabilities = torch.softmax(
            outputs,
            dim=1
        )

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

        all_labels.extend(
            labels.cpu().numpy()
        )

        all_predictions.extend(
            predicted.cpu().numpy()
        )

        all_probabilities.extend(
            probabilities[:, 1].cpu().numpy()
        )

accuracy = correct / total

precision = precision_score(
    all_labels,
    all_predictions
)

recall = recall_score(
    all_labels,
    all_predictions
)

f1 = f1_score(
    all_labels,
    all_predictions
)

classification_rep = classification_report(
    all_labels,
    all_predictions,
    target_names=test_dataset.classes
)

cm = confusion_matrix(
    all_labels,
    all_predictions
)

fpr, tpr, _ = roc_curve(
    all_labels,
    all_probabilities
)

roc_auc = auc(
    fpr,
    tpr
)

precision_curve, recall_curve, _ = precision_recall_curve(
    all_labels,
    all_probabilities
)

print("==========================================")
print("FINAL EVALUATION - ResNet50")
print("==========================================")

print(f"Model: {experiment_name}")
print(f"Test samples: {total}")
print()

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}")
print(f"ROC AUC  : {roc_auc:.4f}")

print("\nClassification Report:")
print(classification_rep)

print("Confusion Matrix:")
print(cm)

results_path = (
    "/content/drive/MyDrive/deepfake_detection/"
    "results/resnet50_test_results.txt"
)

with open(results_path, "w") as f:

    f.write("==========================================\n")
    f.write("FINAL EVALUATION - ResNet50\n")
    f.write("==========================================\n\n")

    f.write(f"Model: {experiment_name}\n")
    f.write(f"Test samples: {total}\n\n")

    f.write(f"Accuracy : {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall   : {recall:.4f}\n")
    f.write(f"F1-score : {f1:.4f}\n")
    f.write(f"ROC AUC  : {roc_auc:.4f}\n\n")

    f.write("Classification Report:\n")
    f.write(classification_rep)

    f.write("\nConfusion Matrix:\n")
    f.write("             Predicted\n")
    f.write(
        "             "
        + "  ".join(test_dataset.classes)
        + "\n"
    )

    for i, row in enumerate(cm):

        f.write(
            f"Actual {test_dataset.classes[i]} "
            + "  ".join(
                str(value)
                for value in row
            )
            + "\n"
        )

print(f"Results saved to:\n{results_path}")

maroon_cmap = LinearSegmentedColormap.from_list(
    "maroon_cmap",
    ["#F5E6E8", "#800020"]
)

fig, ax = plt.subplots(figsize=(7, 6))

im = ax.imshow(
    cm,
    interpolation="nearest",
    cmap=maroon_cmap
)

fig.colorbar(im, ax=ax)

ax.set(
    xticks=np.arange(len(test_dataset.classes)),
    yticks=np.arange(len(test_dataset.classes)),
    xticklabels=test_dataset.classes,
    yticklabels=test_dataset.classes,
    xlabel="Predicted label",
    ylabel="True label",
    title="Confusion Matrix - ResNet50"
)

threshold = cm.max() / 2

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):

        ax.text(
            j,
            i,
            format(cm[i, j], "d"),
            ha="center",
            va="center",
            color="white"
            if cm[i, j] > threshold
            else "black",
            fontsize=13
        )

fig.tight_layout()

plt.savefig(
    f"{figures_dir}/confusion_matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.savefig(
    f"{figures_dir}/confusion_matrix.pdf",
    bbox_inches="tight"
)

plt.show()
plt.close()

maroon = "#800020"

plt.figure(figsize=(8, 6))

plt.plot(
    fpr,
    tpr,
    color=maroon,
    linewidth=2,
    label=f"ResNet50 (AUC = {roc_auc:.4f})"
)

plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    color=maroon,
    linewidth=1.5,
    label="Random classifier"
)

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("ROC Curve - ResNet50")

plt.legend(
    loc="lower right"
)

plt.grid(
    alpha=0.3
)

plt.tight_layout()

plt.savefig(
    f"{figures_dir}/roc_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.savefig(
    f"{figures_dir}/roc_curve.pdf",
    bbox_inches="tight"
)

plt.show()

plt.close()

maroon = "#800020"

plt.figure(figsize=(8, 6))

plt.plot(
    recall_curve,
    precision_curve,
    color=maroon,
    linewidth=2
)

plt.xlabel("Recall")

plt.ylabel("Precision")

plt.title(
    "Precision-Recall Curve - ResNet50"
)

plt.grid(alpha=0.3)

plt.tight_layout()

plt.savefig(
    f"{figures_dir}/precision_recall_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.savefig(
    f"{figures_dir}/precision_recall_curve.pdf",
    bbox_inches="tight"
)

plt.show()

plt.close()

print("All ResNet50 figures saved successfully.")

"""## analysis of potential generalisation



"""

experiment_name = "resnet50_partial_fold4_finetuned"

test_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/test",
    transform=transform
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth",
        map_location=device
    )
)

model = model.to(device)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

test_accuracy = correct / total

print(f"Test Accuracy: {test_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/results/resnet_generalization_comparison.txt",
    "w"
) as f:

    f.write("====================\n")
    f.write("ResNet50 Generalization Analysis\n")
    f.write("====================\n\n")
    f.write("Model: resnet50_partial_fold4_finetuned\n")
    f.write("Training completed after fold4\n")
    f.write(f"Test Accuracy: {test_accuracy:.4f}\n")

print("Fold4 test result saved successfully.")

experiment_name = "resnet50_partial_fold3_finetuned"

test_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/test",
    transform=transform
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth",
        map_location=device
    )
)

model = model.to(device)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

test_accuracy = correct / total

print(f"Test Accuracy: {test_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/results/resnet_generalization_comparison.txt",
    "a"
) as f:

    f.write("\n")
    f.write("Model: resnet50_partial_fold3_finetuned\n")
    f.write("Training completed after fold3\n")
    f.write(f"Test Accuracy: {test_accuracy:.4f}\n")

print("Fold3 test result saved successfully.")

experiment_name = "resnet50_partial_fold2_finetuned"

test_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/test",
    transform=transform
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth",
        map_location=device
    )
)

model = model.to(device)

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

test_accuracy = correct / total

print(f"Test Accuracy: {test_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/results/resnet_generalization_comparison.txt",
    "a"
) as f:

    f.write("\n")
    f.write("Model: resnet50_partial_fold2_finetuned\n")
    f.write("Training completed after fold2\n")
    f.write(f"Test Accuracy: {test_accuracy:.4f}\n")

print("Fold3 test result saved successfully.")

experiment_name = "resnet50_partial_unfreeze"

test_dataset = datasets.ImageFolder(
    "/content/drive/MyDrive/deepfake_detection/deepfake_data/test",
    transform=transform
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        f"/content/drive/MyDrive/deepfake_detection/models/{experiment_name}.pth",
        map_location=device
    )
)

model = model.to(device)
model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(
            outputs,
            1
        )

        total += labels.size(0)

        correct += (
            predicted == labels
        ).sum().item()

test_accuracy = correct / total

print(f"Test Accuracy: {test_accuracy:.4f}")

with open(
    "/content/drive/MyDrive/deepfake_detection/results/resnet_generalization_comparison.txt",
    "a"
) as f:

    f.write("\n")
    f.write("Model: resnet50_partial_unfreeze\n")
    f.write("Training completed after fold1\n")
    f.write(f"Test Accuracy: {test_accuracy:.4f}\n")

print("Fold3 test result saved successfully.")

"""## Grad-CAM visualization"""

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    torch.load(
        "/content/drive/MyDrive/deepfake_detection/models/resnet50_partial_fold5_finetuned.pth",
        map_location=device
    )
)

model = model.to(device)
model.eval()


fake_image_path = (
    "/content/drive/MyDrive/deepfake_detection/"
    "deepfake_data/test/Fake/fake_126.jpg"
)

real_image_path = (
    "/content/drive/MyDrive/deepfake_detection/"
    "deepfake_data/test/Real/real_385.jpg"
)


pil_image_fake = Image.open(
    fake_image_path
).convert("RGB")

pil_image_fake = pil_image_fake.resize(
    (224, 224)
)

input_tensor_fake = transform(
    pil_image_fake
).unsqueeze(0).to(device)

rgb_img_fake = np.array(
    pil_image_fake
).astype(np.float32) / 255.0


pil_image_real = Image.open(
    real_image_path
).convert("RGB")

pil_image_real = pil_image_real.resize(
    (224, 224)
)

input_tensor_real = transform(
    pil_image_real
).unsqueeze(0).to(device)

rgb_img_real = np.array(
    pil_image_real
).astype(np.float32) / 255.0


target_layer = model.layer4[-1]


cam = GradCAM(
    model=model,
    target_layers=[target_layer]
)


grayscale_cam_fake = cam(
    input_tensor=input_tensor_fake
)[0]

visualization_fake = show_cam_on_image(
    rgb_img_fake,
    grayscale_cam_fake,
    use_rgb=True
)


grayscale_cam_real = cam(
    input_tensor=input_tensor_real
)[0]

visualization_real = show_cam_on_image(
    rgb_img_real,
    grayscale_cam_real,
    use_rgb=True
)


plt.figure(figsize=(14, 10))

plt.subplot(2, 2, 1)

plt.imshow(rgb_img_fake)

plt.title("Fake - Original")

plt.axis("off")


plt.subplot(2, 2, 2)

plt.imshow(visualization_fake)

plt.title("Fake - Grad-CAM - ResNet50")

plt.axis("off")


plt.subplot(2, 2, 3)

plt.imshow(rgb_img_real)

plt.title("Real - Original")

plt.axis("off")


plt.subplot(2, 2, 4)

plt.imshow(visualization_real)

plt.title("Real - Grad-CAM - ResNet50")

plt.axis("off")


plt.tight_layout()


os.makedirs(
    "/content/drive/MyDrive/deepfake_detection/figures/resnet50",
    exist_ok=True
)


plt.savefig(
    "/content/drive/MyDrive/deepfake_detection/figures/resnet50/gradcam_fake_real.png",
    dpi=300,
    bbox_inches="tight"
)

plt.savefig(
    "/content/drive/MyDrive/deepfake_detection/figures/resnet50/gradcam_fake_real.pdf",
    bbox_inches="tight"
)

plt.show()

print(
    "ResNet50 Grad-CAM visualization saved successfully."
)